
try{
    console.log(name)
    const name = 'rodrigo barbosa'
}   catch (err){
    console.log('Error:', err)
}

console.log('keep going')